default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: server_development

test:
  <<: *default
  database: server_test

production:
  <<: *default
  database: server_production
  username: server
  password: <%= ENV['SERVER_DATABASE_PASSWORD'] %>
